# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotBar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotBar
  pod 'Alamofire', '~>4.6'
  pod 'Swinject', '~> 2.1.1'
  pod 'SwinjectStoryboard', '~>1.1.2'

  target 'SpotBarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotBarUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
